config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  # Routing dla sesji
get 'login', to: 'sessions#new', as: 'login'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy', as: 'logout'  # Zaktualizowane na DELETE

  # Routing dla rejestracji użytkowników
  get 'signup', to: 'users#new', as: 'signup'
  post 'users', to: 'users#create'

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :employees, only: [:new, :edit, :update] do
    get 'reserve', on: :collection
    patch 'reserve_desk/:id', to: 'employees#reserve_desk', as: 'reserve_desk'
  end

  patch 'reserve_desk/:id', to: 'employees#reserve', as: 'reserve_desk'
  get 'reserve_desk/:id', to: 'employees#reserve_desk', as: 'reserve_desk_form'

  # Routing dla EmployeesController
  get 'employees/reserve', to: 'employees#index', as: 'employees_reserve'
  get 'employees/new', to: 'employees#new', as: 'new_employee_reservation'
  post 'employees', to: 'employees#create'
  get 'employees/:id/edit', to: 'employees#edit', as: 'edit_employee_reservation'
  patch 'employees/:id', to: 'employees#update'
  delete 'employees/:id', to: 'employees#destroy'

  # Routing dla AdminController
  get 'admin/desks/new', to: 'admin#new_desk', as: 'new_desk'
  get 'admin/desks', to: 'admin#desks', as: 'admin_desks'
  post 'admin/desks', to: 'admin#create'
  get 'admin/desks/:id/edit', to: 'admin#edit', as: 'edit_desk'
  patch 'admin/desks/:id', to: 'admin#update', as: 'update_desk'
  delete 'admin/desks/:id', to: 'admin#delete'
  delete 'admin/desks/:id', to: 'admin#destroy_desk', as: 'destroy_desk'

  # Dodatkowe routingi
  get "up" => "rails/health#show", as: :rails_health_check

  # Możesz tu zdefiniować główną ścieżkę, jeśli chcesz
  # root "some_controller#some_action"
end

app/models/user.rb
class User < ApplicationRecord
  has_one :reservation

  # has_secure_password używa bcrypt do bezpiecznego przechowywania haseł
  has_secure_password

  # Walidacja obecności i unikalności email
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  # Atrybut wskazujacy czy użytkownik ma uprawnienia administratora
  attribute :admin, default: false
  def admin?
    admin
  end
  # Możesz dodać inne walidacje zgodnie z potrzebami aplikacji
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id # Logowanie użytkownika po rejestracji
      redirect_to user_path(@user), notice: 'Rejestracja zakończona pomyślnie.'
    else
      render :new
    end
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
  end

  # GET /users/:id/edit
  def edit
    # set_user jest używany
  end

  # PATCH/PUT /users/:id
  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Profil zaktualizowany pomyślnie.'
    else
      render :edit
    end
  end

  # DELETE /users/:id
  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Profil usunięty pomyślnie.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def require_login
    redirect_to login_path, alert: 'Musisz być zalogowany.' unless logged_in?
  end

  def correct_user
    redirect_to(root_url, alert: "Nie masz uprawnień do tej operacji.") unless @user == current_user
  end

  def check_if_admin
    if current_user.admin?
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edytowanie Profilu</h1>

<%= form_with model: @user, url: user_path(@user), method: :patch do |form| %>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>

  <div class="actions">
    <%= form.submit "Aktualizuj" %>
  </div>
<% end %>

<%= link_to 'Powrót', user_path(@user) %>

app/views/users/new.html.erb
<h1>Rejestracja</h1>

<%= form_with model: @user, url: users_path do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :admin %><br>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit "Rejestruj" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profil Użytkownika</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edytuj profil', edit_user_path(@user) %> |
<%= link_to 'Przejdź do rezerwacji', reserve_employees_path %> |
<%= link_to 'Powrót', root_path %>